development: &default
  adapter: postgresql
  database: ballyhooweb_development_2
  encoding: utf8
  min_messages: warning
  pool: 5
  username: postgres
  password: postgres
  timeout: 50000


test: &test
  <<: *default
  database: ballyhooweb_test_2

cucumber:
  <<: *test